# Generated by Django 2.2.2 on 2019-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TD', 'To Do'), ('D', 'Done')], default='TD', max_length=100),
        ),
    ]
